apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  ports: #123
    - name: http  
      port: 80
      targetPort: 80
    - name: https  
      port: 443
      targetPort: 443
  selector:
    app: nginx
